### ISSUE TITLE
Basic Auth Failure Handling

### ISSUE THREAD

**Issue by mAd-DaWg** [serviejs/popsicle-basic-auth#4]
Upon failure of basic auth, a 401 response is sent, however before popsicle gives the response it is getting stuck on the basic auth challenge(where it would show a popup in a users browser). This then waits for user interaction(which can't happen) causing the request to timeout instead of giving the 401 response.

You can use https://httpbin.org/basic-auth/cool/bens
with a "Authorization: Basic Y29vbDpiZWFucw==" header
for testing, where "Y29vbDpiZWFucw==" is "cool:beans" base64 encoded

**Comment by blakeembrey** [comment]
This isn't really an issue with popsicle, it's just how browsers work - this would happen any time you do a HTTP request in a browser unfortunately. Try some of the suggestions in things like https://stackoverflow.com/questions/9859627/how-to-prevent-browser-to-invoke-basic-auth-popup-and-handle-401-error-using-jqu (you should just be able to remove the header the browser is responding to here).

**Comment by blakeembrey** [comment]
Closing since it's a browser behaviour, nothing built into popsicle. Although I'm happy to hack around it if there is a way to do so, I just haven't heard of anything client side to do this.

**Comment by blakeembrey** [comment]
This is the best solution I've come across myself: https://stackoverflow.com/a/20221330/1090990. Happy to add this to the README.

**Comment by mAd-DaWg** [comment]
Hmm, i have tried all of those, but they don't work :/
